databases:
  - name: task_manager_db
    plan: free
    databaseName: task_manager
    user: task_manager

services:
  - type: web
    plan: free
    name: task_manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uv run python3 -m gunicorn task_manager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
