# Generated by Django 5.1.4 on 2025-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя статуса')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
